### ISSUE TITLE
Next tasks (Sep 2022)

### ISSUE THREAD

**Issue by ChloeRN** [GhanSaridnirun/Green-Peafowl-Population_Project__GS#12]
Issues to address / changes to make in base model:

- [x] Update initial values for p and p.init
- [x] Use count data of ALL females instead of just "breeding females"
- [x] Change process model to reflect using data on all females
- [x] Split and update time indices (ny.year and ny.sim)
- [x] After making above changes: test run
- [x] Visualize results

Extensions to the base model:

- [x]  Include males [#13] 
- [x]  Split females into breeders vs. non-breeders [#14, optional*]
- [x]  Add additional data on reproduction (chick/female from camera traps, field data on brood size) [#15] 
- [ ]  Refine informative priors [#16] 

*This extension is not necessary and should not be prioritized. What we could get from it is (potentially) estimation of a breeding proportion parameter.

**Comment by ChloeRN** [comment]
Extensions to the base model: 

- [ ] Include males
- [ ] Split females into breeders vs. non-breeders (optional*)
- [ ] Add additional data on reproduction (chick/female from camera traps, field data on brood size)
- [ ] Refine informative priors

*This extension is not necessary and should not be prioritized. What we could get from it is (potentially) estimation of a breeding proportion parameter.
